[SL-803] Scaffold parsers
stoplightio/markdown pull request #1
Opened 2018-12-03 12:45 UTC by P0lip

2018-12-04 01:40 UTC, marbemac requested changes
Looks pretty good, put in a few small suggestions. In addition:

- [x] lint errors need to be fixed, try `yarn test.prod`
- [x] formatting is incorrect, try `yarn lint.fix` (or perhaps get your IDE auto-formatting if its not?)
- [x] is it pre-mature to add the transformers and ast-types code over? should we leave it out for now and just rely on base unist types (that can be overridden w generics), and then add it later when we need to?

2018-12-04 01:40 UTC, marbemac commented on src/ast-types/smdast/element.ts
> +import * as Unist from '@core/unist';
Legacy `@core` import. However, not sure if we should move these ast-types over until we have a better idea how we'll use them in this package.

2018-12-04 01:40 UTC, marbemac commented on src/index.ts
> +// export * from './parseWithPointers';
We should probably just export the parse and parseWithPointers functions as well for this library. It's the primary purpose. And take the corresponding sentence out of the readme about it not being exported from root.

2018-12-04 01:40 UTC, marbemac commented on src/parseWithPointers.ts
> +const getPointers = (node: Partial<TUnist.IParent>, pointers: Pointers = {}, path: string = '/'): Pointers  => {
Should return [IParserResultPointers](https://github.com/stoplightio/types/blob/master/src/parsers.ts#L23).

2018-12-04 01:40 UTC, marbemac commented on src/parseWithPointers.ts
> +export const parseWithPointers = (value: string, opts?: ParseOpts, processor?: Processor): IParserResult<Mdast.IRoot> => {
Suggest add generic, and default to plain unist structure. Users of the library (like slate), can pass in the custom Mdast.IRoot type.

2018-12-04 08:59 UTC, P0lip commented
Yeah, I had TSLint turned off for this project, that's why I had Prettier off.
I removed those transformers and indeed this is something very specific to Slate for now.

2018-12-04 22:33 UTC, P0lip commented
@marbemac comments addressed

2018-12-05 14:51 UTC, marbemac approved these changes

2018-12-05 14:52 UTC, merged

2018-12-05 14:53 UTC, marbemac commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stoplight/markdown)
- [GitHub release](https://github.com/stoplightio/markdown/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: